### ISSUE TITLE
Bind variadic parameters list

### ISSUE THREAD

**Issue by thibaultCha** [jbochi/lua-resty-cassandra#30]
According to [this](https://issues.apache.org/jira/browse/CASSANDRA-4210) feature, and given this prepared statement:

```
UPDATE some_table SET counter = counter + 1 WHERE col1 = ? AND period IN (?);
```

Does lua-resty-cassandra support the binding of such a parameter (the second one)? I cannot find any information cassandra's documentation or the definition of the binary protocol about how such a parameter should be binded to the statement.

I also noticed that the prepared statement returns this for the column: 

```lua
{
  keyspace = "some_keyspace",
  name = "period",
  table = "some_table",
  type = {
    id = 13
  }
}
```

It seems that `id = 13` (`0x0D`) is of type `varchar`. So it seems like the statement is expecting a string for this parameter.

I tried using some of the types (`cassandra.list` for example) with no success. Any help about wether or not this feature is supported, or how to support it (where to find documentation about it, as it would be my pleasure to contribute to the driver) would be greatly appreciated.

Thanks!

**Comment by jbochi** [comment]
I was not aware of this feature, thanks for letting me know.

It actually worked without any code modification. See 49ce1d8 for an example.

As in the [nodejs driver](https://datastax-oss.atlassian.net/browse/NODEJS-49?focusedCommentId=18747&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-18747), you should not use parenthesis  in the CQL string and the argument should be a list (annotated with cassandra.list)

Let me know if this works for you.

**Comment by thibaultCha** [comment]
Damn! I did try without the parenthesis, but I missed to combine this with `cassandra.list`!

It works very well, thank you!

**Comment by jbochi** [comment]
you're welcome!
