### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by jbochi** [jbochi/lua-resty-cassandra#34]
A lot of features are not described in the readme (paging, batch support, all type annotation functions, etc)

Should we have a wiki? Create a website? Just update the readme?

**Comment by thibaultCha** [comment]
:+1: for the README update. Also, the method themselves could use some documentation!

**Comment by thibaultCha** [comment]
I started to update the documentation on [this branch](https://github.com/thibaultCha/lua-resty-cassandra/tree/documentation).

The layout is an attempt, if you don't like it, let me know.

We also need a changelog file.

**Comment by jbochi** [comment]
Awesome! Feel free to send another pull request.

And yes, we definitely need a changelog.
