### ISSUE TITLE
Accepting multiple hosts with different ports when connecting

### ISSUE THREAD

**Issue by thefosk** [jbochi/lua-resty-cassandra#55]
Right now it's only possible to specify different hosts, but not different ports. It would be useful to be able to execute something like this instead:

```lua
connect("1.1.1.1:9042", "2.2.2.2:4123", "3.3.3.3:51231")
```

or

```lua
connect({ host = "1.1.1.1", port = 9042 }, 
        { host = "2.2.2.2", port = 4123 },
        { host = "3.3.3.3", port = 51231})
```

**Comment by thibaultCha** [comment]
I can implement that if you want @jbochi

**Comment by jbochi** [comment]
That's a nice idea. Feel free to send a pull request :)
